// seed-data.js — injected via <script> tag (file:// compatible, no fetch)
window.SEED_BOOKS = [
  { id:'BK001', title:'핸즈온 머신러닝 (3판)', authors:['오렐리앙 제롱'], translators:['박해선'],
    category:'데이터/AI', price:45000, coverColor:'#1F4E79',
    hasLectureMaterial:true, digitalAvailable:true,
    description:'사이킷런·케라스·텐서플로를 활용한 머신러닝·딥러닝 기초부터 실전.' },
  { id:'BK002', title:'밑바닥부터 시작하는 딥러닝', authors:['사이토 고키'], translators:['개앞맵시'],
    category:'데이터/AI', price:30000, coverColor:'#2C5F2E',
    hasLectureMaterial:true, digitalAvailable:true,
    description:'numpy만으로 직접 구현하며 딥러닝 원리를 이해하는 입문서.' },
  { id:'BK003', title:'파이썬 라이브러리를 활용한 데이터 분석 (3판)', authors:['웨스 맥키니'], translators:['김형준'],
    category:'데이터/AI', price:38000, coverColor:'#5C4033',
    hasLectureMaterial:false, digitalAvailable:true,
    description:'pandas·numpy·matplotlib 등 데이터 분석 핵심 라이브러리 실전 가이드.' },
  { id:'BK004', title:'Do it! 점프 투 파이썬', authors:['박응용'], translators:[],
    category:'프로그래밍', price:22000, coverColor:'#E65100',
    hasLectureMaterial:true, digitalAvailable:true,
    description:'국내 최다 독자를 보유한 파이썬 입문 교재.' },
  { id:'BK005', title:'이것이 자바다 (3판)', authors:['신용권','임경균'], translators:[],
    category:'프로그래밍', price:36000, coverColor:'#1A237E',
    hasLectureMaterial:true, digitalAvailable:true,
    description:'자바 기초부터 고급 개념까지 실습 중심으로 다루는 표준 교재.' },
  { id:'BK006', title:'혼자 공부하는 파이썬', authors:['윤인성'], translators:[],
    category:'프로그래밍', price:24000, coverColor:'#4A148C',
    hasLectureMaterial:true, digitalAvailable:false,
    description:'기초 문법부터 클래스까지 혼자서도 완주할 수 있는 독학 교재.' },
  { id:'BK007', title:'C 프로그래밍: 원리와 실제 (5판)', authors:['Al Kelley','Ira Pohl'], translators:['곽용재'],
    category:'프로그래밍', price:33000, coverColor:'#37474F',
    hasLectureMaterial:true, digitalAvailable:false,
    description:'C 언어의 원리와 실제 프로그래밍 기법을 깊이 있게 다루는 고전 교재.' },
  { id:'BK008', title:'데이터베이스 개론 (3판)', authors:['김연희'], translators:[],
    category:'DB/네트워크', price:30000, coverColor:'#0D47A1',
    hasLectureMaterial:true, digitalAvailable:true,
    description:'관계형 데이터베이스 이론부터 SQL 실습까지 체계적으로 학습하는 교재.' },
  { id:'BK009', title:'SQL 첫걸음', authors:['아사이 아츠시'], translators:['박준용'],
    category:'DB/네트워크', price:26000, coverColor:'#006064',
    hasLectureMaterial:false, digitalAvailable:true,
    description:'SELECT부터 서브쿼리까지 SQL 기초를 쉽게 배우는 입문서.' },
  { id:'BK010', title:'컴퓨터 네트워크 (하향식 접근 8판)', authors:['James Kurose','Keith Ross'], translators:['최종원 외'],
    category:'DB/네트워크', price:42000, coverColor:'#1B5E20',
    hasLectureMaterial:true, digitalAvailable:false,
    description:'응용 계층부터 물리 계층까지 하향식으로 배우는 네트워크 표준 교재.' },
  { id:'BK011', title:'운영체제 (10판)', authors:['Abraham Silberschatz','Peter Galvin'], translators:['조유근 외'],
    category:'OS/알고리즘', price:43000, coverColor:'#4E342E',
    hasLectureMaterial:true, digitalAvailable:false,
    description:'프로세스·스레드·메모리 관리·파일 시스템까지 운영체제 전반을 다루는 대표 교재.' },
  { id:'BK012', title:'자료구조와 알고리즘 (2판)', authors:['이관용','박진하'], translators:[],
    category:'OS/알고리즘', price:28000, coverColor:'#880E4F',
    hasLectureMaterial:true, digitalAvailable:true,
    description:'C/Java 기반의 자료구조 이론과 알고리즘 분석을 실습으로 배우는 교재.' },
  { id:'BK013', title:'이산수학 (6판)', authors:['Kenneth Rosen'], translators:['김대수'],
    category:'OS/알고리즘', price:38000, coverColor:'#4A148C',
    hasLectureMaterial:true, digitalAvailable:false,
    description:'논리·집합·그래프·조합론 등 컴퓨터 과학의 수학적 기초 필수 교재.' },
  { id:'BK014', title:'HTML5+CSS3+자바스크립트 웹 프로그래밍', authors:['윤인성'], translators:[],
    category:'웹/모바일', price:32000, coverColor:'#E64A19',
    hasLectureMaterial:true, digitalAvailable:true,
    description:'HTML5·CSS3·자바스크립트를 한 권에 담은 웹 표준 입문 교재.' },
  { id:'BK015', title:'안드로이드 앱 프로그래밍 (개정 4판)', authors:['고돈호'], translators:[],
    category:'웹/모바일', price:35000, coverColor:'#1B5E20',
    hasLectureMaterial:false, digitalAvailable:true,
    description:'코틀린으로 실전 안드로이드 앱을 개발하는 단계별 학습 교재.' },
  { id:'BK016', title:'이공계 수학 (5판)', authors:['박정호'], translators:[],
    category:'수학/통계', price:31000, coverColor:'#0D47A1',
    hasLectureMaterial:true, digitalAvailable:false,
    description:'미적분·선형대수·미분방정식을 공학 응용 사례와 함께 학습하는 교재.' },
  { id:'BK017', title:'통계학 개론 (5판)', authors:['김우철 외'], translators:[],
    category:'수학/통계', price:27000, coverColor:'#006064',
    hasLectureMaterial:true, digitalAvailable:true,
    description:'기술통계부터 추측통계·회귀분석까지 체계적으로 다루는 표준 통계 교재.' },
];

window.SEED_USERS = [
  {
    id:'prof_kmj', loginId:'kmj',
    name:'김민정', title:'교수',
    university:'서울대학교', department:'컴퓨터공학과',
    email:'kmj@snu.ac.kr', phone:'010-1234-5678',
    role:'professor', grade:'S',
    registeredAt:'2022-03-01', verifiedAt:'2022-03-05',
    courses:['머신러닝','딥러닝','데이터사이언스입문'],
    students:280,
    note:'서울대 CS 주임교수. 대형 강의 담당. VIP 관리 필요.',
  },
  {
    id:'prof_lsh', loginId:'lsh',
    name:'이상훈', title:'교수',
    university:'연세대학교', department:'소프트웨어학부',
    email:'lsh@yonsei.ac.kr', phone:'010-2345-6789',
    role:'professor', grade:'A',
    registeredAt:'2023-01-15', verifiedAt:'2023-01-20',
    courses:['자바프로그래밍','운영체제','알고리즘'],
    students:150,
    note:'자바·알고리즘 분야 전문가. 교재 직접 집필 경험 있음.',
  },
  {
    id:'prof_pjy', loginId:'pjy',
    name:'박지영', title:'교수',
    university:'부산대학교', department:'정보컴퓨터공학부',
    email:'pjy@pusan.ac.kr', phone:'010-3456-7890',
    role:'professor', grade:'B',
    registeredAt:'2024-03-01', verifiedAt:'2024-03-10',
    courses:['데이터베이스','웹프로그래밍'],
    students:90,
    note:'부산 지역 신규 관리 교수. 채택 실적 성장 중.',
  },
  {
    id:'prof_jhw', loginId:'jhw',
    name:'정현우', title:'강사',
    university:'한양대학교', department:'컴퓨터소프트웨어학부',
    email:'jhw@hanyang.ac.kr', phone:'010-4567-8901',
    role:'professor', grade:'New',
    registeredAt:'2026-05-10', verifiedAt:null,
    courses:['파이썬프로그래밍기초'],
    students:45,
    note:'전환신청 검토 중. 재직증명서 제출 완료.',
    verificationDocs:{ employment:true, courseplan:true, id:false },
  },
  {
    id:'sales_01', loginId:'sales01',
    name:'최영업', title:'영업 담당자',
    university:null, department:null,
    email:'sales01@hanbit.co.kr', phone:'02-325-5544',
    role:'sales', grade:null,
  },
  {
    id:'admin_01', loginId:'admin01',
    name:'김팀장', title:'교강사 영업팀장',
    university:null, department:null,
    email:'admin01@hanbit.co.kr', phone:'02-325-5544',
    role:'admin', grade:null,
  },
];

// ── 견본 신청 이력 (과거 학기 포함) ────────────────────────────────
window.SEED_SAMPLE_REQUESTS = [
  // ── 김민정 (S등급) ──────────
  { id:'SR001', professorId:'prof_kmj', bookId:'BK001', type:'paper', status:'approved',
    requestedAt:'2025-09-05', processedAt:'2025-09-08', semester:'2025-2',
    courseName:'머신러닝', expectedStudents:95,
    address:'서울시 관악구 관악로 1, 302동 405호', memo:'강의 교재 검토', assignedTo:'sales_01' },
  { id:'SR002', professorId:'prof_kmj', bookId:'BK002', type:'paper', status:'approved',
    requestedAt:'2025-09-07', processedAt:'2025-09-10', semester:'2025-2',
    courseName:'딥러닝', expectedStudents:88,
    address:'서울시 관악구 관악로 1, 302동 405호', memo:'', assignedTo:'sales_01' },
  { id:'SR003', professorId:'prof_kmj', bookId:'BK003', type:'ebook', status:'approved',
    requestedAt:'2025-09-10', processedAt:'2025-09-12', semester:'2025-2',
    courseName:'데이터분석', expectedStudents:60, address:'', memo:'', assignedTo:'sales_01' },
  { id:'SR004', professorId:'prof_kmj', bookId:'BK001', type:'paper', status:'approved',
    requestedAt:'2026-03-05', processedAt:'2026-03-08', semester:'2026-1',
    courseName:'머신러닝', expectedStudents:95,
    address:'서울시 관악구 관악로 1, 302동 405호', memo:'', assignedTo:'sales_01' },
  { id:'SR005', professorId:'prof_kmj', bookId:'BK002', type:'paper', status:'approved',
    requestedAt:'2026-03-07', processedAt:'2026-03-10', semester:'2026-1',
    courseName:'딥러닝', expectedStudents:88,
    address:'서울시 관악구 관악로 1, 302동 405호', memo:'', assignedTo:'sales_01' },
  { id:'SR006', professorId:'prof_kmj', bookId:'BK004', type:'ebook', status:'pending',
    requestedAt:'2026-05-25', processedAt:null, semester:'2026-1',
    courseName:'데이터사이언스입문', expectedStudents:100, address:'', memo:'2학기 준비', assignedTo:'sales_01' },

  // ── 이상훈 (A등급) ──────────
  { id:'SR010', professorId:'prof_lsh', bookId:'BK005', type:'paper', status:'approved',
    requestedAt:'2025-09-04', processedAt:'2025-09-07', semester:'2025-2',
    courseName:'자바프로그래밍', expectedStudents:72,
    address:'서울시 서대문구 연세로 50, 공학관 601호', memo:'', assignedTo:'sales_01' },
  { id:'SR011', professorId:'prof_lsh', bookId:'BK011', type:'paper', status:'approved',
    requestedAt:'2025-09-05', processedAt:'2025-09-09', semester:'2025-2',
    courseName:'운영체제', expectedStudents:65,
    address:'서울시 서대문구 연세로 50, 공학관 601호', memo:'', assignedTo:'sales_01' },
  { id:'SR012', professorId:'prof_lsh', bookId:'BK012', type:'ebook', status:'approved',
    requestedAt:'2025-09-08', processedAt:'2025-09-11', semester:'2025-2',
    courseName:'알고리즘', expectedStudents:55, address:'', memo:'', assignedTo:'sales_01' },
  { id:'SR013', professorId:'prof_lsh', bookId:'BK005', type:'paper', status:'approved',
    requestedAt:'2026-03-04', processedAt:'2026-03-07', semester:'2026-1',
    courseName:'자바프로그래밍', expectedStudents:72,
    address:'서울시 서대문구 연세로 50, 공학관 601호', memo:'자바 수업 채택 예정', assignedTo:'sales_01' },
  { id:'SR014', professorId:'prof_lsh', bookId:'BK011', type:'ebook', status:'pending',
    requestedAt:'2026-05-20', processedAt:null, semester:'2026-1',
    courseName:'운영체제', expectedStudents:60, address:'', memo:'온라인 수업용', assignedTo:'sales_01' },
  { id:'SR015', professorId:'prof_lsh', bookId:'BK013', type:'paper', status:'approved',
    requestedAt:'2026-03-10', processedAt:'2026-03-13', semester:'2026-1',
    courseName:'이산수학', expectedStudents:45,
    address:'서울시 서대문구 연세로 50, 공학관 601호', memo:'', assignedTo:'sales_01' },

  // ── 박지영 (B등급) ──────────
  { id:'SR020', professorId:'prof_pjy', bookId:'BK008', type:'paper', status:'approved',
    requestedAt:'2025-09-08', processedAt:'2025-09-12', semester:'2025-2',
    courseName:'데이터베이스', expectedStudents:48,
    address:'부산시 금정구 부산대학로63번길 2, 정보관 302호', memo:'', assignedTo:'sales_01' },
  { id:'SR021', professorId:'prof_pjy', bookId:'BK014', type:'ebook', status:'approved',
    requestedAt:'2025-09-10', processedAt:'2025-09-14', semester:'2025-2',
    courseName:'웹프로그래밍', expectedStudents:42, address:'', memo:'', assignedTo:'sales_01' },
  { id:'SR022', professorId:'prof_pjy', bookId:'BK008', type:'paper', status:'approved',
    requestedAt:'2026-03-10', processedAt:'2026-03-14', semester:'2026-1',
    courseName:'데이터베이스', expectedStudents:48,
    address:'부산시 금정구 부산대학로63번길 2, 정보관 302호', memo:'', assignedTo:'sales_01' },
  { id:'SR023', professorId:'prof_pjy', bookId:'BK009', type:'ebook', status:'pending',
    requestedAt:'2026-05-22', processedAt:null, semester:'2026-1',
    courseName:'SQL실습', expectedStudents:35, address:'', memo:'SQL 실습 수업용', assignedTo:'sales_01' },
];

// ── 강의자료 다운로드 이력 ────────────────────────────────────────
window.SEED_MATERIAL_REQUESTS = [
  // 김민정
  { id:'MR001', professorId:'prof_kmj', bookId:'BK001', status:'approved',
    requestedAt:'2025-09-10', processedAt:'2025-09-11', downloadedAt:'2025-09-12',
    coursePlanFile:null, memo:'' },
  { id:'MR002', professorId:'prof_kmj', bookId:'BK002', status:'approved',
    requestedAt:'2025-09-12', processedAt:'2025-09-13', downloadedAt:'2025-09-15',
    coursePlanFile:null, memo:'' },
  { id:'MR003', professorId:'prof_kmj', bookId:'BK001', status:'approved',
    requestedAt:'2026-03-12', processedAt:'2026-03-13', downloadedAt:'2026-03-14',
    coursePlanFile:null, memo:'재다운로드' },
  { id:'MR004', professorId:'prof_kmj', bookId:'BK004', status:'pending',
    requestedAt:'2026-05-25', processedAt:null, downloadedAt:null,
    coursePlanFile:null, memo:'' },
  // 이상훈
  { id:'MR010', professorId:'prof_lsh', bookId:'BK005', status:'approved',
    requestedAt:'2025-09-11', processedAt:'2025-09-12', downloadedAt:'2025-09-14',
    coursePlanFile:null, memo:'' },
  { id:'MR011', professorId:'prof_lsh', bookId:'BK011', status:'approved',
    requestedAt:'2026-03-11', processedAt:'2026-03-12', downloadedAt:'2026-03-14',
    coursePlanFile:null, memo:'' },
  { id:'MR012', professorId:'prof_lsh', bookId:'BK012', status:'approved',
    requestedAt:'2026-03-15', processedAt:'2026-03-16', downloadedAt:null,
    coursePlanFile:null, memo:'' },
  // 박지영
  { id:'MR020', professorId:'prof_pjy', bookId:'BK008', status:'approved',
    requestedAt:'2025-09-15', processedAt:'2025-09-16', downloadedAt:'2025-09-18',
    coursePlanFile:null, memo:'' },
  { id:'MR021', professorId:'prof_pjy', bookId:'BK008', status:'approved',
    requestedAt:'2026-03-15', processedAt:'2026-03-16', downloadedAt:null,
    coursePlanFile:null, memo:'재다운로드' },
];

// ── 채택 신고 이력 ────────────────────────────────────────────────
window.SEED_ADOPTIONS = [
  // 김민정 — 과거 학기
  { id:'AD001', professorId:'prof_kmj', bookId:'BK001', semester:'2025-2',
    courseName:'머신러닝', sections:2, expectedStudents:95,
    coursePlanFile:'SNU_CS_머신러닝_2025-2.pdf',
    reportedAt:'2025-10-05', status:'confirmed', confirmedAt:'2025-10-08' },
  { id:'AD002', professorId:'prof_kmj', bookId:'BK002', semester:'2025-2',
    courseName:'딥러닝', sections:1, expectedStudents:88,
    coursePlanFile:'SNU_CS_딥러닝_2025-2.pdf',
    reportedAt:'2025-10-05', status:'confirmed', confirmedAt:'2025-10-08' },
  // 김민정 — 현재 학기
  { id:'AD003', professorId:'prof_kmj', bookId:'BK001', semester:'2026-1',
    courseName:'머신러닝', sections:2, expectedStudents:95,
    coursePlanFile:'SNU_CS_머신러닝_2026-1.pdf',
    reportedAt:'2026-04-05', status:'confirmed', confirmedAt:'2026-04-08' },
  { id:'AD004', professorId:'prof_kmj', bookId:'BK002', semester:'2026-1',
    courseName:'딥러닝', sections:1, expectedStudents:88,
    coursePlanFile:'SNU_CS_딥러닝_2026-1.pdf',
    reportedAt:'2026-04-05', status:'confirmed', confirmedAt:'2026-04-08' },

  // 이상훈
  { id:'AD010', professorId:'prof_lsh', bookId:'BK005', semester:'2025-2',
    courseName:'자바프로그래밍', sections:2, expectedStudents:72,
    coursePlanFile:'YSU_자바_2025-2.pdf',
    reportedAt:'2025-10-06', status:'confirmed', confirmedAt:'2025-10-10' },
  { id:'AD011', professorId:'prof_lsh', bookId:'BK011', semester:'2025-2',
    courseName:'운영체제', sections:1, expectedStudents:65,
    coursePlanFile:'YSU_OS_2025-2.pdf',
    reportedAt:'2025-10-06', status:'confirmed', confirmedAt:'2025-10-10' },
  { id:'AD012', professorId:'prof_lsh', bookId:'BK005', semester:'2026-1',
    courseName:'자바프로그래밍', sections:2, expectedStudents:72,
    coursePlanFile:'YSU_자바_2026-1.pdf',
    reportedAt:'2026-04-10', status:'pending', confirmedAt:null },

  // 박지영
  { id:'AD020', professorId:'prof_pjy', bookId:'BK008', semester:'2025-2',
    courseName:'데이터베이스', sections:1, expectedStudents:48,
    coursePlanFile:'PNU_DB_2025-2.pdf',
    reportedAt:'2025-10-12', status:'confirmed', confirmedAt:'2025-10-16' },
  { id:'AD021', professorId:'prof_pjy', bookId:'BK008', semester:'2026-1',
    courseName:'데이터베이스', sections:1, expectedStudents:48,
    coursePlanFile:'PNU_DB_2026-1.pdf',
    reportedAt:'2026-04-15', status:'pending', confirmedAt:null },
];

window.SEED_NOTIFICATIONS = [
  { id:'N001', userId:'prof_kmj', type:'approval', message:'[SR004] 핸즈온 머신러닝 견본 도서 발송 완료되었습니다.', createdAt:'2026-03-08', read:true },
  { id:'N002', userId:'prof_lsh', type:'approval', message:'[SR013] 이것이 자바다 견본 도서 발송 완료되었습니다.', createdAt:'2026-03-07', read:true },
  { id:'N003', userId:'prof_kmj', type:'info', message:'2026년 2학기 교재 채택 등록 기간이 시작되었습니다 (5/26~6/30).', createdAt:'2026-05-26', read:false },
  { id:'N004', userId:'prof_lsh', type:'pending', message:'[SR014] 운영체제 전자책 견본 신청이 검토 중입니다.', createdAt:'2026-05-20', read:false },
  { id:'N005', userId:'admin_01', type:'verify', message:'정현우 강사의 교수 회원 전환 신청이 접수되었습니다.', createdAt:'2026-05-10', read:false },
  { id:'N006', userId:'admin_01', type:'verify', message:'[SR014] 이상훈 교수의 전자책 견본 신청 승인이 필요합니다.', createdAt:'2026-05-20', read:false },
];

// ── 비회원 임시 ID 교강사 5명 ─────────────────────────────────────
window.SEED_TEMP_PROFESSORS = [
  {
    id:'temp_001', loginId:null,
    name:'홍길동', title:'교수',
    university:'고려대학교', department:'전산학과',
    email:'hgd@korea.ac.kr', phone:'010-5678-9012',
    role:'professor', grade:null,
    isTemp:true, registeredAt:null, verifiedAt:null,
    courses:['프로그래밍입문','자료구조'], students:120,
    assignedTo:'sales_01',
    note:'파이썬 교재 관심. 도서 목록 전달 완료.',
  },
  {
    id:'temp_002', loginId:null,
    name:'최수진', title:'교수',
    university:'성균관대학교', department:'소프트웨어학과',
    email:'csj@skku.ac.kr', phone:'010-6789-0123',
    role:'professor', grade:null,
    isTemp:true, registeredAt:null, verifiedAt:null,
    courses:['데이터구조','알고리즘설계'], students:85,
    assignedTo:'sales_01',
    note:'이산수학 교재 문의. 다음 학기 채택 고려 중.',
  },
  {
    id:'temp_003', loginId:null,
    name:'강태우', title:'조교수',
    university:'경희대학교', department:'컴퓨터공학과',
    email:'ktw@khu.ac.kr', phone:'010-7890-1234',
    role:'professor', grade:null,
    isTemp:true, registeredAt:null, verifiedAt:null,
    courses:['운영체제론','시스템프로그래밍'], students:60,
    assignedTo:'sales_01',
    note:'운영체제 10판 관심. 영문판 vs 번역판 비교 중.',
  },
  {
    id:'temp_004', loginId:null,
    name:'임지원', title:'강사',
    university:'인하대학교', department:'정보통신공학과',
    email:'ljw@inha.ac.kr', phone:'010-8901-2345',
    role:'professor', grade:null,
    isTemp:true, registeredAt:null, verifiedAt:null,
    courses:['네트워크보안','웹서비스'], students:45,
    assignedTo:'sales_01',
    note:'컴퓨터 네트워크 교재 견본 요청 예정.',
  },
  {
    id:'temp_005', loginId:null,
    name:'윤서현', title:'교수',
    university:'한국외국어대학교', department:'경영정보학과',
    email:'ysh@hufs.ac.kr', phone:'010-9012-3456',
    role:'professor', grade:null,
    isTemp:true, registeredAt:null, verifiedAt:null,
    courses:['경영정보시스템','데이터베이스활용'], students:75,
    assignedTo:'sales_01',
    note:'SQL 첫걸음 교재 관심. 비전공자 대상 강의.',
  },
];

// ── 등급 변경 이력 ────────────────────────────────────────────────
window.SEED_GRADE_HISTORY = [
  // 김민정: 신규→A→S(수동보정)
  { id:'GH001', professorId:'prof_kmj', fromGrade:null,  toGrade:'New', type:'auto',
    reasonCategory:'초기등록', reason:'신규 교수회원 등록',
    adjustedBy:'system', adjustedAt:'2022-03-05' },
  { id:'GH002', professorId:'prof_kmj', fromGrade:'New', toGrade:'A',   type:'auto',
    reasonCategory:'자동산정', reason:'2022년 1학기 채택 2종 (서울대 중대형) 기준 A등급 자동 산정',
    adjustedBy:'system', adjustedAt:'2022-09-01' },
  { id:'GH003', professorId:'prof_kmj', fromGrade:'A',   toGrade:'S',   type:'manual',
    reasonCategory:'전략대학', reason:'서울대 CS학과 주임교수 취임. 전략 대학 VIP 관리 기준 S등급 수동 보정.',
    adjustedBy:'admin_01', adjustedAt:'2023-03-01' },
  // 이상훈: 신규→A
  { id:'GH010', professorId:'prof_lsh', fromGrade:null,  toGrade:'New', type:'auto',
    reasonCategory:'초기등록', reason:'신규 교수회원 등록',
    adjustedBy:'system', adjustedAt:'2023-01-20' },
  { id:'GH011', professorId:'prof_lsh', fromGrade:'New', toGrade:'A',   type:'auto',
    reasonCategory:'자동산정', reason:'2023년 하반기 채택 3종 이상 달성 기준 A등급 자동 산정',
    adjustedBy:'system', adjustedAt:'2023-09-01' },
  // 박지영: 신규→B
  { id:'GH020', professorId:'prof_pjy', fromGrade:null,  toGrade:'New', type:'auto',
    reasonCategory:'초기등록', reason:'신규 교수회원 등록',
    adjustedBy:'system', adjustedAt:'2024-03-10' },
  { id:'GH021', professorId:'prof_pjy', fromGrade:'New', toGrade:'B',   type:'auto',
    reasonCategory:'자동산정', reason:'2024년 1학기 채택 1종 달성 기준 B등급 자동 산정',
    adjustedBy:'system', adjustedAt:'2024-09-01' },
];

// ── 영업 접촉 이력 (메모) ─────────────────────────────────────────
window.SEED_CONTACT_NOTES = [
  { id:'CN001', professorId:'prof_kmj',
    content:'2026년 2학기 머신러닝 교재 추가 채택 논의. 핸즈온 머신러닝 3판 + 밑바닥 딥러닝 패키지 제안. 긍정적 반응.',
    createdBy:'sales_01', createdAt:'2026-05-15' },
  { id:'CN002', professorId:'prof_kmj',
    content:'학과 세미나 초청 강사 연결 요청. 출판사 저자 섭외 지원 예정. 다음 주 회신.',
    createdBy:'admin_01', createdAt:'2026-04-20' },
  { id:'CN003', professorId:'prof_kmj',
    content:'2025년 2학기 대규모 채택(2분반 190명) 감사 방문. 교재 품질 만족, 보조자료 추가 요청.',
    createdBy:'sales_01', createdAt:'2025-11-10' },
  { id:'CN010', professorId:'prof_lsh',
    content:'이것이 자바다 최신판 출간 사전 안내. 3판 출간 예정 (2026년 하반기). 사전 검토본 발송 예정.',
    createdBy:'sales_01', createdAt:'2026-05-10' },
  { id:'CN011', professorId:'prof_lsh',
    content:'알고리즘 교재 추가 채택 논의. 이산수학 견본 발송 완료. 다음 학기 채택 의향 확인.',
    createdBy:'sales_01', createdAt:'2026-03-20' },
  { id:'CN020', professorId:'prof_pjy',
    content:'부산대 방문. 데이터베이스 수업 교재 만족도 확인. SQL 첫걸음 추가 채택 의향 있음.',
    createdBy:'sales_01', createdAt:'2026-04-05' },
];
